# Generated by Django 3.2.9 on 2022-03-18 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20220126_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
