# Generated by Django 3.2.9 on 2022-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='league',
            field=models.TextField(blank=True, choices=[('L1', 'god'), ('L2', 'gold'), ('L3', 'silver'), ('L4', 'bronze'), ('L5', 'no league')], default='L5', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
